### ISSUE TITLE
Sweep: When installing for a first time user (assume they have 0 tickets created), state a prompt that this may take 

### ISSUE THREAD

**Issue by wwzeng1** [sweepai/sweep#1100]
### Details

we could do a better job at saying “hey, the estimate of indexing the codebase/code search will take X minutes”, since you can approximate from the repo size
the logic is in on_ticket.py

use the github api to get the total number of files
1000 files ~ 1 minute of indexing

**Comment by johnpccd** [comment]
Generation should be random.. generate a random number and based on that either add this strategy or that.. same way how we either generate a StrategyChaser or a StrategyAreaDefender.
Instead of adding only a SpawnInfo, add a full SpawnSequence using:
 l.AddRange(new List<Coach.SpawnSequence> {
                new Coach.SpawnSequence{
