### ISSUE TITLE
Sweep: get_ticket_count in chat_logger.py should not rate limit users for the day if they have less than zero tickets

### ISSUE THREAD

**Issue by wwzeng1** [sweepai/sweep#1161]

**Comment by MeDott29** [comment]
sweep-webhook-1      | Exception in thread Thread-3 (run_on_ticket):                                                                                      sweep-webhook-1      | Traceback (most recent call last):                                                                                                 sweep-webhook-1      |   File "/usr/local/lib/python3.10/threading.py", line 1016, in _bootstrap_inner                                                    sweep-webhook-1      |     self.run()                                                                                                                     sweep-webhook-1      |   File "/usr/local/lib/python3.10/threading.py", line 953, in run                                                                  sweep-webhook-1      |     self._target(*self._args, **self._kwargs)                                                                                      sweep-webhook-1      |   File "/app/sweepai/api.py", line 90, in run_on_ticket                                                                            sweep-webhook-1      |     return on_ticket(*args, **kwargs, tracking_id=tracking_id)                                                                     sweep-webhook-1      |   File "/app/sweepai/handlers/on_ticket.py", line 1639, in on_ticket                                                               sweep-webhook-1      |     raise e                                                                                                                        sweep-webhook-1      |   File "/app/sweepai/handlers/on_ticket.py", line 425, in on_ticket                                                                sweep-webhook-1      |     daily_tickets_used=chat_logger.get_ticket_count(use_date=True),                                                                sweep-webhook-1      | AttributeError: 'NoneType' object has no attribute 'get_ticket_count'  

I'm trying to get the self hosting to work... not sure what to do
