### ISSUE TITLE
Sweep: Implement support for GitLab

### ISSUE THREAD

**Issue by aslafy-z** [sweepai/sweep#1180]
### Details

As a GitLab user, I'd like sweep to monitor issues and produce merge requests on my GitLab projects.
You'll have to implement an abstraction that adds support for both GitLab and GitHub and leave room for potential other implementations.
You can use the [python-gitlab](https://python-gitlab.readthedocs.io/) package to interact with GitLab. 
Implement tests for these two implementations.

This is a test PR, but I'd love to see a real support for GitLab some day :)

### Files to change

```shell
sweepai/config/server.py
sweepai/core/sweep_bot.py
sweepai/handlers/on_ticket.py
sweepai/handlers/on_comment.py
sweepai/handlers/create_pr.py
sweepai/config/client.py
sweepai/api.py
sweepai/events.py
sweepai/core/vector_db.py
sweepai/handlers/on_review.py
```

**Comment by AntonOsika** [comment]
Are you planning to add support for gitlab @wwzeng1?

Depict.ai would be very interested in paying if it works on our gitlab codebase.
