### ISSUE TITLE
Sweep: Support for Azure DevOps

### ISSUE THREAD

**Issue by chaoscreater** [sweepai/sweep#1224]
### Details

Please make this compatible with Azure DevOps!

Checklist:

- [X] `sweepai/api.py`
> Modify the existing API endpoints to be more generic and add new endpoints for Azure DevOps.

- [X] `sweepai/handlers/create_pr.py`
> Modify the handler for creating pull requests to support Azure DevOps.

- [X] `sweepai/handlers/on_comment.py`
> Modify the handler for comments to support Azure DevOps.

- [X] `sweepai/core/sweep_bot.py`
> Modify the core bot functionalities to work with Azure DevOps.

**Comment by wwzeng1** [comment]
Hey @chaoscreater, unfortunately we're not focused on Azure devops. maybe in the future though! thanks for the suggestion
