### ISSUE TITLE
Sweep: When there is an error that occurs "Unable to Complete PR"  in sweepai/handlers/on_ticket.py surface better error message for debugging

### ISSUE THREAD

**Issue by wmaiouiru** [sweepai/sweep#1236]
### Details

When there is an error that occurs with message "Unable to Complete PR"  in sweepai/handlers/on_ticket.py surface better error message for debugging

The type of AI GPT-4 vs. GPT-3.5 is edited out. 
Perhaps adding an run id would help with debugging as well.

### Files to change

```shell
sweepai/handlers/on_ticket.py
```

<details>
<summary>Checklist</summary>

- [X] `sweepai/handlers/on_ticket.py`
> * At the start of the `on_ticket` function, generate a unique run id and store it in a variable named `run_id`. You can use the `uuid` module to generate a unique id.
> • In the error handling part of the `on_ticket` function, modify the error message to include the type of AI and the run id. You can use the `use_faster_model` variable to determine the type of AI. Include these information in the error message in a clear and informative way.

</details>

**Comment by wwzeng1** [comment]
Thanks for the PR William, we currently have an internal tool that let's us search through all of this as well as see the metadata! This is mostly for user messages, which should be alright :)
