### ISSUE TITLE
Sweep: Pronlem with Function

### ISSUE THREAD

**Issue by Diae98** [sweepai/sweep#1291]
### Details

`class Home(UserControl):
    def __init__(self):
        super().__init__()
    
    Title = Text("Login Page",
                 size=24,
                 italic=True,
                 color=colors.WHITE,
                 )
    Text_Name = TextField(hint_text="What's your name? ",
                          text_size=18,
                          autofocus=True,
                          icon=icons.PERSON_2_OUTLINED,
                          width=250,
                          max_length=16,
                          )
    Button_Name = ElevatedButton(text="Subtim",
                                  width=100,
                                  height=60,
                                  animate_offset=Animation(200,AnimationCurve.EASE_IN_CUBIC),
                                  bgcolor=colors.DEEP_PURPLE_ACCENT_700,
                                  color=colors.WHITE,
                                  on_click=lambda e: self.page_go_to_chat_page(e)
                                       
                                  )
    def page_go_to_chat_page(self, e):
        if self.Text_Name.value == "":
            self.Text_Name.error_text = "Please enter your Name!"
            self.update()
        else:
            self.page.go('/chat_page')`

Name Error: name 'self' is not defined

<details>
<summary>Checklist</summary>

- [ ] `sweepai/core/code_repair.py`
> * Instruction 1: Check the 'CodeRepairChecker' and 'CodeRepairer' classes for any misuse of the 'self' keyword. Ensure that 'self' is being used to access all class attributes and methods.
> • Instruction 2: In the 'check_code' method of the 'CodeRepairChecker' class, ensure that 'self' is being used to call the 'chat' method.
> • Instruction 3: In the 'CodeRepairer' class, ensure that 'self' is being used to access the 'code_repair_checker' attribute.

- [ ] `sweepai/core/chat.py`
> * Instruction 1: Check the 'ChatGPT' class for any misuse of the 'self' keyword. Ensure that 'self' is being used to access all class attributes and methods.
> • Instruction 2: In the 'chat' method of the 'ChatGPT' class, ensure that 'self' is being used to access the 'model' and 'messages' attributes.

- [ ] `sweepai/core/entities.py`
> * Instruction 1: Check the 'Message' class for any misuse of the 'self' keyword. Ensure that 'self' is being used to access all class attributes and methods.

- [ ] `sweepai/core/prompts.py`
> * Instruction 1: Check the 'code_repair_check_system_prompt', 'code_repair_check_prompt', 'code_repair_system_prompt', and 'code_repair_prompt' functions for any misuse of the 'self' keyword. Since these are functions and not class methods, they should not be using the 'self' keyword at all.

- [ ] `sweepai/core/sandbox.py`
> * Instruction 1: Check the 'Sandbox' class for any misuse of the 'self' keyword. Ensure that 'self' is being used to access all class attributes and methods.
> • Instruction 2: In the 'from_token', 'run_command', 'clone_repo', 'create_python_venv', and 'close' methods of the 'Sandbox' class, ensure that 'self' is being used to access the necessary class attributes and methods.

</details>

**Comment by kevinlu1248** [comment]
Hey I'm a developer of Sweep and we're taking a look at this.
