### ISSUE TITLE
Is 5 GPT4 tickets per month for OSS version as well?

### ISSUE THREAD

**Issue by veeral-patel** [sweepai/sweep#1304]
### Details

Thank you for this project, I've been waiting for something like this for a long time!

From the README:

> Every user receives unlimited GPT-3.5 tickets and 5 GPT-4 tickets per month. To prevent abuse, users can use 2 GPT-4 tickets a day.

I don't get this - is this for Sweep's SaaS product or does it apply to the open source project as well? Not sure how it would apply to the open source project - how would a OSS project be able to enforce this?

In general the Pricing section is confusing - how is there a price if the project is open source?

**Comment by kevinlu1248** [comment]
This is just for the hosted product. We can clarify further in the pricing section. This can be turned off for self-hosted deployments.

**Comment by veeral-patel** [comment]
Sounds good. Going to close.
