### ISSUE TITLE
Run on Code Llama 2 locally 

### ISSUE THREAD

**Issue by Ashraf-Ali-aa** [sweepai/sweep#1400]
### Details

A nice feature would be able to run sweep on code Llama 2 , here is a tool https://ollama.ai/ that allows you to run llama2 locally also its possible to run different models 

<details open>
<summary>Checklist</summary>

- [X] `sweepai/api.py`
> • Add a new function named `run_code_llama_2_locally`. This function should take as input the necessary parameters for running Code Llama 2.
> • In the `run_code_llama_2_locally` function, add code to call the appropriate Code Llama 2 functions. Handle any errors that may occur and return the results in a format that is consistent with the rest of the Sweep project.
> • Integrate the `run_code_llama_2_locally` function into the existing Sweep project. This means it should be callable from the appropriate places in the code.

</details>

**Comment by wwzeng1** [comment]
Hey @Ashraf-Ali-aa we're on this!
