### ISSUE TITLE
Sweep: broken link https://docs.sweep.dev/tutorial

### ISSUE THREAD

**Issue by TonyBagnall** [sweepai/sweep#1408]
### Details

link from here https://github.com/sweepai/sweep/blob/main/docs/installation.md
called "[tutorial on running Sweep on Docusaurus](https://docs.sweep.dev/tutorial)."

goes to a 404 link

### Files to change

```shell
https://github.com/sweepai/sweep/blob/main/docs/installation.md
```

<details open>
<summary>Checklist</summary>

- [X] `docs/installation.md`
> • Find the line containing the text "[tutorial on running Sweep on Docusaurus](https://docs.sweep.dev/tutorial)."
> • Replace the existing URL "https://docs.sweep.dev/tutorial" with the correct URL for the tutorial on running Sweep on Docusaurus.

</details>

**Comment by kevinlu1248** [comment]
sweep: Retry

**Comment by kevinlu1248** [comment]
Thanks for reporting this! @TonyBagnall
