### ISSUE TITLE
Sweep: Update broken deployment link in README.md (https://docs.sweep.dev/usage/deployment) to the working link (https://docs.sweep.dev/deployment)

### ISSUE THREAD

**Issue by chrislengerich** [sweepai/sweep#1416]
### Details

Update broken deployment link in README.md (https://docs.sweep.dev/usage/deployment) to the working link (https://docs.sweep.dev/deployment)

<details open>
<summary>Checklist</summary>

- [X] `README.md`
> • Locate the incorrect link (https://docs.sweep.dev/usage/deployment) in the README.md file.
> • Replace the incorrect link with the correct one (https://docs.sweep.dev/deployment).
> • Save the changes to the README.md file.

</details>

**Comment by wwzeng1** [comment]
Thank you @chrislengerich! Super cool that you founded CodeCompose, would have loved to try it. Sorry you caught Sweep at a bad time, we just migrated to our self hosted version last night
