### ISSUE TITLE
Sweep: Are there any plans to support gitlab?

### ISSUE THREAD

**Issue by juunone** [sweepai/sweep#1470]
### Details

Any plans to support gitlab?
Using sweep through gitlab CI/CD would be very helpful for juniors in my company,   
but it doesn't seem to be supported yet.  
I wonder if there are any plans to support it?

<details open>
<summary>Checklist</summary>

- [X] `sweepai/gitlab_api.py`
> • Create a new Python file named gitlab_api.py in the sweepai directory.
> • In this file, define a class named GitLabAPI that will handle the GitLab API integration.
> • This class should have methods for each of the GitLab API endpoints that we need to interact with. These methods should handle making the API request and processing the response.
> • Include error handling to manage any issues that might arise when making the API requests.

- [X] `sweepai/api.py`
> • In the api.py file, import the GitLabAPI class from the gitlab_api.py file.
> • Modify the existing functions that interact with the GitHub API to also work with the GitLab API. This might involve adding conditional logic to determine which API to use based on the user's configuration.
> • Ensure that any changes made to support the GitLab API do not break the existing GitHub API integration.

- [X] `docs/installation.md`
> • Update the installation instructions in the docs/installation.md file to include information about the new GitLab support.
> • This should include any additional steps needed to configure the GitLab API integration.
> • Also update any other sections of the documentation that reference the GitHub API to also mention the GitLab API.

- [X] `tests/test_gitlab_api.py`
> • Create a new Python file named test_gitlab_api.py in the tests directory.
> • In this file, write unit tests for the GitLabAPI class and its methods. These tests should ensure that the GitLab API integration works as expected and handles errors correctly.

</details>

**Comment by wwzeng1** [comment]
@juunone Not at the moment, but would be happy to take contributions!
