### ISSUE TITLE
Sweep: the README uses https in the github url but we need to use git:

### ISSUE THREAD

**Issue by dataf3l** [sweepai/sweep#2082]
### Details

to solve this issue:

Cloning into 'sweep.'...
remote: Support for password authentication was removed on August 13, 2021.
remote: Please see https://docs.github.com/en/get-started/getting-started-with-git/about-remote-repositories#cloning-with-https-urls for information on currently recommended modes of authentication.
fatal: Authentication failed for 'https://github.com/sweepai/sweep./'

maybe change README.md

**Comment by kevinlu1248** [comment]
I just ran this on a remote machine with default Git settings:
```
╰─ git clone https://github.com/sweepai/sweep
Cloning into 'sweep'...
remote: Enumerating objects: 41572, done.
remote: Counting objects: 100% (2078/2078), done.
remote: Compressing objects: 100% (841/841), done.
remote: Total 41572 (delta 1464), reused 1788 (delta 1236), pack-reused 39494
Receiving objects: 100% (41572/41572), 44.86 MiB | 28.84 MiB/s, done.
Resolving deltas: 100% (27423/27423), done.
```

What OS are you on?
