### ISSUE TITLE
Make posthog integration optional

### ISSUE THREAD

**Issue by asc11cat** [sweepai/sweep#235]
https://github.com/sweepai/sweep/blob/2914f8e5e5b96eab1085b1910a3e09643a553b3f/sweepai/utils/event_logger.py#L8

Results in the following error when `POSTHOG_API_KEY` is not passed:

```
Traceback (most recent call last):
  File "/pkg/modal/_container_entrypoint.py", line 330, in handle_input_exception
    yield
  File "/pkg/modal/_container_entrypoint.py", line 403, in call_function_sync
    res = fun(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^
  File "/root/sweepai/handlers/on_ticket.py", line 86, in on_ticket
    posthog.capture(username, "started", properties=metadata)
    ^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'capture'
```

To prevent this, we can init the instance with an empty key and use `posthog.disabled = True`

**Comment by asc11cat** [comment]
https://github.com/sweepai/sweep/issues/236

**Comment by asc11cat** [comment]
https://github.com/sweepai/sweep/pull/239

**Comment by asc11cat** [comment]
@wwzeng1

**Comment by kevinlu1248** [comment]
@asc11cat Have you tested this?

**Comment by asc11cat** [comment]
@kevinlu1248 yep, please check #257, I've added some stuff after testing

**Comment by kevinlu1248** [comment]
Thanks for the help @asc11cat
