### ISSUE TITLE
Ignore @mentions in issues/pr's

### ISSUE THREAD

**Issue by asc11cat** [sweepai/sweep#244]
A good idea would be to ignore messages that only contain mentions

![image](https://github.com/sweepai/sweep/assets/47783525/b18a17d0-a77c-4f3c-914c-774a374140b9)

**Comment by kevinlu1248** [comment]
We can do it by character count or by "Sweep:" prefix.

**Comment by kevinlu1248** [comment]
We do it by "Sweep:" prefix now so this is fixed.
