### ISSUE TITLE
Sweep: Fix importerror: cannot import name 'self' from 'typing'

### ISSUE THREAD

**Issue by hamero** [sweepai/sweep#259]
### Description

when running `python sweepai/app/cli.py`

### Relevant files

```shell
sweepai/app/cli.py
```

**Comment by wwzeng1** [comment]
This issue seems to come from when your python version is <3.10

**Comment by kevinlu1248** [comment]
@hamero I fixed this bug a while back, just make sure you're using the latest sweep on pip. Thanks!
