### ISSUE TITLE
Sweep: running against a local git repo

### ISSUE THREAD

**Issue by Casper321** [sweepai/sweep#2667]
### Details

Feature request: is it possible to run Sweep against a local git repo (not connecting it to Github) and working with a CLI or something similar?

**Comment by Casper321** [comment]
Cool! If I would like to clone the code and try to do this myself, do you have some guidance on how to start?

**Comment by kevinlu1248** [comment]
@Casper321 It would involve changing all the GitHub calls to file read/writes. However, I believe aider is closer to what you are looking for: https://aider.chat/.
