### ISSUE TITLE
Sweep: Add Cohere for embeddings with VECTOR_EMBEDDING_SOURCE of "cohere"

### ISSUE THREAD

**Issue by Tantalon** [sweepai/sweep#2954]
### Details

We recently compared several AI tools. Sweep is awesome! However, we found it to be weaker in identifying relevant sections of code to modify. One of the best results we saw was a ~20% improvement by moving from OpenAI embeddings to Cohere embeddings.

Can Sweep add Cohere support to itself?

<img width="1321" alt="image" src="https://github.com/sweepai/sweep/assets/761257/f4df9624-1511-4a94-843f-b2017912a529">

**Comment by kevinlu1248** [comment]
Thanks for the suggestion! Is this benchmark open-source? We actually currently completely rely on lexical search, all the vector DB code is dead code. Let's chat more on [Discord](https://discord.gg/sweep) or Slack.
