### ISSUE TITLE
Sweep: The requested model 'gpt-4-0125-preview' does not exist

### ISSUE THREAD

**Issue by akashcommit** [sweepai/sweep#3053]
### Details
I am trying to run sweep self hosted and followed the official document. 
I am getting error related to OPEN AI version , kindly advice how can I configure  open ai  version.

Error Message:
```
The requested model 'gpt-4-0125-preview' does not exist.
```

**Comment by kevinlu1248** [comment]
It's currently not configurable, we just search and replace everywhere for the old model every time a new model comes out but would love to take a PR.

**Comment by kevinlu1248** [comment]
@akashcommit This is now possible by setting the `DEFAULT_GPT4_32K_MODEL` flag! It now defaults to GPT 1106 instead of 0125 since we found that it performs a lot better.
