### ISSUE TITLE
sweep-sandbox script setup cannot work

### ISSUE THREAD

**Issue by CharlonTank** [sweepai/sweep#3072]
On line 35 in https://github.com/sweepai/sweep/blob/main/bin/install_sweep_sandbox.sh, there is a `cd sweep/sweepai/sandbox` that cannot work because sandbox directory does not exist on the main branch:
```bash
bash-3.2$ git clone https://github.com/sweepai/sweep.git --depth 1
Cloning into 'sweep'...
remote: Enumerating objects: 604, done.
remote: Counting objects: 100% (604/604), done.
remote: Compressing objects: 100% (522/522), done.
remote: Total 604 (delta 80), reused 427 (delta 61), pack-reused 0
Receiving objects: 100% (604/604), 2.76 MiB | 2.92 MiB/s, done.
Resolving deltas: 100% (80/80), done.
bash-3.2$ cd sweep/sweepai/sandbox
bash: cd: sweep/sweepai/sandbox: No such file or directory
```

https://github.com/sweepai/sweep/blob/743e44cc18f6e91229219fb3980dfea9177cb21f/bin/install_sweep_sandbox.sh#L35

**Comment by kevinlu1248** [comment]
Hey thanks for reporting. The sandbox has been deprecated, we just forgot to delete this script.

**Comment by CharlonTank** [comment]
Thank you for your answer @kevinlu1248 could you tell me if https://docs.sweep.dev/usage/sandbox is also deprecated doc too? If so is there still a way to use a typechecker?
