### ISSUE TITLE
get_scores for days_since_last_modified is wrong

### ISSUE THREAD

**Issue by esperyong** [sweepai/sweep#3083]
### Details
Branch: feat/context-benchmark
Bugs: sweepai/utils/scorer.py

```python
def get_factors(commits):
    commit_count = len(commits) + 1
    earliest_commit = commits[0].committed_datetime if commits else datetime.now()
    current_time = datetime.now()
    tz_info = earliest_commit.astimezone().tzinfo
    if tz_info:
        current_time = datetime.now().astimezone(tz_info)
        earliest_commit = earliest_commit.astimezone(tz_info)
    days_since_last_modified = (
        max(
            ((current_time - earliest_commit).total_seconds() // 3600),
            0,
        )
        + 1
    )
    return (1, commit_count, days_since_last_modified)

def convert_to_percentiles(values, max_percentile=0.25):
    sorted_values = sorted(values)  # Sort the values in ascending order
    n = len(sorted_values)
    percentile_mapping = {
        value: (i / (n)) * max_percentile for i, value in enumerate(sorted_values)
    }
    percentiles = [
        percentile_mapping[value] for value in values
    ]  # Create the percentiles list based on the mapping

    return percentiles


def get_scores(score_factors):
    # add all of the arrays together
    line_count_scores = [x[0] for x in score_factors]
    commit_count_scores = [x[1] for x in score_factors]
    days_since_last_modified_scores = [x[2] for x in score_factors]
    line_count_scores = convert_to_percentiles(line_count_scores, 1)
    commit_count_scores = convert_to_percentiles(commit_count_scores, 1)
    days_since_last_modified_scores = convert_to_percentiles(
        days_since_last_modified_scores, 1
    )
    scores = [
        sum(x)
        for x in zip(
            line_count_scores, commit_count_scores, days_since_last_modified_scores
        )
    ]
    return convert_to_percentiles(scores, 0.25)
```

In the code above, the usage of days_since_last_modified is the same as that of commit_count. However, this should be incorrect. Because the higher the commit_count, the
higher the score should be. But, the higher the days_since_last_modified, the lower the score should be. Because the 
**The more commits a file has, the more valuable it is.** 
**The more recently a file was modified, the better.**

<details open>
<summary>Checklist</summary>

- [X] Modify `sweepai/utils/scorer.py` ✓ https://github.com/sweepai/sweep/commit/661be69484e0a0eac45e8ae97d1de93ed60312a9 [Edit](https://github.com/sweepai/sweep/edit/sweep/feat/context-benchmark_215db/sweepai/utils/scorer.py#L40-L55)
- [X] Running GitHub Actions for `sweepai/utils/scorer.py` ✓  [Edit](https://github.com/sweepai/sweep/edit/sweep/feat/context-benchmark_215db/sweepai/utils/scorer.py#L40-L55)
- [ ] Modify `sweepai/utils/scorer.py` ▶  [Edit](https://github.com/sweepai/sweep/edit/sweep/feat/context-benchmark_215db/sweepai/utils/scorer.py)
- [ ] Running GitHub Actions for `sweepai/utils/scorer.py` ▶  [Edit](https://github.com/sweepai/sweep/edit/sweep/feat/context-benchmark_215db/sweepai/utils/scorer.py)
</details>

**Comment by wwzeng1** [comment]
Thanks Esper! This is great, I'll run sweep on this one.
