### ISSUE TITLE
Sweep: error with docker on mac m1

### ISSUE THREAD

**Issue by rawwerks** [sweepai/sweep#3157]
### Details
Bugs: after following the installation instructions and pulling the docker image, i get this error: 
```
webhook  | 12:C 23 Feb 2024 23:51:21.222 # Fatal error, can't open config file '/app/redis.conf': No such file or directory
webhook  | python: can't open file '/app/sweepai/watch.py': [Errno 2] No such file or directory
webhook exited with code 0
```
i am running mac m1 chip with docker desktop

<details open>
<summary>Checklist</summary>

- [X] Modify `docker-compose.yml` ✓ https://github.com/sweepai/sweep/commit/951ae86915165affa37f7bcef6fa24b97d300a51 [Edit](https://github.com/sweepai/sweep/edit/sweep/error_with_docker_on_mac_m1/docker-compose.yml)
- [X] Running GitHub Actions for `docker-compose.yml` ✓  [Edit](https://github.com/sweepai/sweep/edit/sweep/error_with_docker_on_mac_m1/docker-compose.yml)
</details>

**Comment by alwaysgoodtime** [comment]
I hava the same question, too.

**Comment by kevinlu1248** [comment]
<div align='center'><a href="https://github.com/sweepai/sweep"><img class="swing" src="https://raw.githubusercontent.com/sweepai/sweep/main/.assets/sweeping.gif" width="100" style="width:50px; margin-bottom:10px" alt="Sweeping"></a></div><div align='center'>

<h2>✨ Track Sweep's progress on our <a href="https://sweep-trilogy.vercel.app/issues/010893dcc2">progress dashboard</a>!</h2></div><br/><div align='center'>

<img src='https://progress-bar.dev/0/?&title=Progress&width=600' alt='0%' /></div>

<div align='center'>💎 <b>Sweep Pro</b>: I'm using GPT-4. You have unlimited GPT-4 tickets. (tracking ID: <code>010893dcc2</code>)</div>

---
> [!TIP]
> I can email you when I complete this pull request if you set up your email [here](https://sweep-trilogy.vercel.app/profile)!

---
## Actions (click)
- [ ] ↻ Restart Sweep

---
I am currently looking into this ticket! I will update the progress of the ticket in this comment. I am currently searching through your code, looking for relevant snippets.

---
## Step 1: 🔎 Searching
I'm searching for relevant snippets in your repository. If this is your first time using Sweep, I'm indexing your repository. You can monitor the progress using the progress dashboard

---

<details>
<summary><b>🎉 Latest improvements to Sweep:</b></summary>
<ul>
<li>New <a href="https://sweep-trilogy.vercel.app">dashboard</a> launched for real-time tracking of Sweep issues, covering all stages from search to coding.</li>
<li>Integration of OpenAI's latest Assistant API for more efficient and reliable code planning and editing, improving speed by 3x.</li>
<li>Use the <a href="https://marketplace.visualstudio.com/items?itemName=GitHub.vscode-pull-request-github">GitHub issues extension</a> for creating Sweep issues directly from your editor.</li>
</ul>
</details>


💡 To recreate the pull request edit the issue title or description.
<sup>Something wrong? [Let us know](https://discord.gg/sweep).</sup>

**Comment by kevinlu1248** [comment]
Sorry for the late response, I'll take a look and update it.

**Comment by kevinlu1248** [comment]
Should be fixed now.
