### ISSUE TITLE
Community help wanted: evaluate Sweep on SWE-Bench

### ISSUE THREAD

**Issue by wwzeng1** [sweepai/sweep#3283]
References: https://www.swebench.com/#
We'll cover all associated OpenAI costs. We'll also give you some pointers over a call.

Reply to this issue if you're interested!

**Comment by garyhlai** [comment]
Hi @wwzeng1 I'm interested. Just shot you a message on Discord.

**Comment by wwzeng1** [comment]
Hey Gary, thanks for the response. Here's our PR for you to look over + understand https://github.com/sweepai/sweep/pull/3318

**Comment by GravityPhone** [comment]
Hey!   Might be fun, I'm interested.
