### ISSUE TITLE
Sweep: 

### ISSUE THREAD

**Issue by Muyixone** [sweepai/sweep#453]
### Description

**The documentation link on the landing page is broken.**
![Sweep_404_error](https://github.com/sweepai/sweep/assets/66142660/1c7e1e94-e40b-426f-9b65-1087ce492b3e)

**Comment by kevinlu1248** [comment]
Our landing page is actually on https://github.com/sweepai/landing-page but we will fix this.

**Comment by kevinlu1248** [comment]
This is fixed now.
