### ISSUE TITLE
Sweep: suggesting multiple changes to a file in a review reverts previous changes in subsequent commits

### ISSUE THREAD

**Issue by lasa01** [sweepai/sweep#455]
### Description

Suggesting multiple changes in a Sweep pull request review causes Sweep to first create a commit with one of the changes correctly applied. In the subsequent commits made by Sweep, however, the correct change in Sweep's previous commit gets reverted alongside with the other suggested change. Making individual comments about changes and waiting for Sweep to create a commit before suggesting another change works correctly.

Here's an example about the situation: https://github.com/lasa01/ExtCord/pull/11 . See commits https://github.com/lasa01/ExtCord/pull/11/commits/86a8bcee29118ad8cf710a2ae06e8dbacd7f5cf0 and https://github.com/lasa01/ExtCord/pull/11/commits/e17ccdd06bf192fa308b139b6b83ca477905b7cf . The correct suggestion was applied in the first linked commit, but reverted in the second one alongside another implemented suggestion.

**Comment by lasa01** [comment]
Seems like this might be just a coincidence. Sweep just reverted some changes it made earlier even when creating a single comment about a suggestion. It was deleting some imports, maybe it just likes to do that :D

**Comment by wwzeng1** [comment]
Got it, this seems to be due to a race condition with how we process changes. We should put these in a queue instead. Thanks for the callout!

**Comment by kevinlu1248** [comment]
sweep: retry
