### ISSUE TITLE
Sweep is adding line numbers to the beginning of Markdown files.

### ISSUE THREAD

**Issue by claudiofcguerra** [sweepai/sweep#549]
Great job on Sweep guys.

I'm testing it out and when modifying README.md files it's adding line numbers to the beginning of the lines for some reason.

![image](https://github.com/sweepai/sweep/assets/91799686/33cb1fb5-9045-4953-91d7-a98f5319378f)

**Comment by wwzeng1** [comment]
Thank you for reporting this!
