### ISSUE TITLE
Sweep: Fix the error `No module named 'sweepai.utils.config.client'; 'sweepai.utils.config' is not a package`

### ISSUE THREAD

**Issue by sagarspatil** [sweepai/sweep#575]
### Description

(venv) PS C:\software\python\sweep> python sweepai/app/cli.py  
Traceback (most recent call last):
  File "C:\software\python\sweep\sweepai\app\ui.py", line 16, in <module>
    from sweepai.utils.config.client import SweepConfig
ModuleNotFoundError: No module named 'sweepai.utils.config.client'; 'sweepai.utils.config' is not a package

### Relevant files

```shell
sweep\sweepai\app\ui.py
```

**Comment by kevinlu1248** [comment]
sweep: retry

**Comment by kevinlu1248** [comment]
@sagarspatil Can you make an empty `__init__.py` in sweepai/utils/config/__init__.py?
