### ISSUE TITLE
Sweep: ui.py is not found when executing 'sweep' command

### ISSUE THREAD

**Issue by Breisoft** [sweepai/sweep#580]
### Description

Hi @sweepai Team,

I'm experiencing an issue when trying to install and run sweepai in a Python 3.11 virtual environment on MacOS. After following the recommended installation process and running the sweep command, Python can't seem to find the ui.py file in the sweepai app directory, even though it's there. It's not using the venv path, but is looking for a folder within the directory.

Here's the detailed information regarding the issue:

OS: MacOS
Python version: 3.11.4_1
Sweepai version: 0.5.1
Below are the commands I used and the respective output:

```bash
➜  upwork-rss python3.11 -m venv .venv
➜  upwork-rss source .venv/bin/activate
(.venv) ➜  upwork-rss pip3 install --force-reinstall sweepai && sweep
```

Output:

```bash
⭐ Remember to star our repo at https://github.com/sweepai/sweep! 
/opt/homebrew/Cellar/python@3.11/3.11.4_1/Frameworks/Python.framework/Versions/3.11/Resources/Python.app/Contents/MacOS/Python: can't open file '/Users/josh/My Drive/BreisoftLLC/upwork-rss/sweepai/app/ui.py': [Errno 2] No such file or directory
```

From the error, it appears that the application is unable to locate the ui.py file in the specified directory, though it **is** present. Any assistance on how to solve this problem would be greatly appreciated.

I'm successfully able to authenticate the github repo, but after that, the command fails. I've tried to replicate this, but even uninstalling the library, the github authentication stays.

Note: I've also tried this in my global Python installation instead of a venv and get the same issue. 

Kind regards,
Josh

**Comment by kevinlu1248** [comment]
@Breisoft Can you downgrade to `sweepai==0.5.0` for now? It's a bug in the latest release.

**Comment by Breisoft** [comment]
Sure, thank you

**Comment by Breisoft** [comment]
Actually, that doesn't appear to work either:

```bash
(.venv) ➜  upwork-rss sweep                      
⭐ Remember to star our repo at https://github.com/sweepai/sweep! 
/opt/homebrew/Cellar/python@3.11/3.11.4_1/Frameworks/Python.framework/Versions/3.11/Resources/Python.app/Contents/MacOS/Python: can't open file '/Users/josh/My Drive/BreisoftLLC/upwork-rss/sweepai/app/ui.py': [Errno 2] No such file or directory
```

```bash
(.venv) ➜  upwork-rss pip3 show sweepai
Name: sweepai
Version: 0.5.0
Summary: Sweep software chores
Home-page: 
Author: Kevin Lu
Author-email: 
License: 
Location: /Users/josh/My Drive/BreisoftLLC/upwork-rss/.venv/lib/python3.11/site-packages
Requires: config-path, GitPython, gradio, loguru, PyGithub, pyyaml, requests, tabulate, typer, urllib3
Required-by: 
```

**Comment by Breisoft** [comment]
if I cd directly into the directory containing the file, it does work

**Comment by kevinlu1248** [comment]
We're you running this from source or from pip?

**Comment by Breisoft** [comment]
pip:

```bash
pip3 install sweepai==0.5.0  
```

I tried sweep's branch fix as well from source, and that also didn't fix the issue. The only thing that's worked as of now is directly cd'ing into site-packages of the venv

**Comment by kevinlu1248** [comment]
Ya source has a potential bug currently. When you ran it from pip, were you cloned into the repo (this would cause 
problems)? Also, https://github.com/sweepai/sweep/pull/586 should fix this but it's untested.

**Comment by Breisoft** [comment]
Nah I got rid of the repo and created a new venv

**Comment by kevinlu1248** [comment]
Makes sense, will have this fixed. You can try https://github.com/sweepai/sweep/pull/586 for now

**Comment by wwzeng1** [comment]
Closing this due to Sweep chat deprecation
