### ISSUE TITLE
File age as code search rank factor

### ISSUE THREAD

**Issue by tobiasmuehl** [sweepai/sweep#684]
Just read your [article](https://docs.sweep.dev/blogs/building-code-search) on what factors go into code search. I want to suggest another factor:

- The older a file is, the more likely it is that the file plays a key role in the repo

**Comment by wwzeng1** [comment]
That's a good point! Thanks Tobias. Let's try to get Sweep to run this.

**Comment by wwzeng1** [comment]
https://github.com/sweepai/sweep/issues/690

**Comment by wwzeng1** [comment]
This is done!
