### ISSUE TITLE
Sweep: When creating a new file, make sure there is a newline char at the end of the file.

### ISSUE THREAD

**Issue by pseudomata** [sweepai/sweep#910]
### Details

Currently when Sweep opens a PR with a change that introduces a new file, it does not terminate the file with a newline character. This is likely to fail many linters and shows the small 🚫 sign in the GitHub UI.

**Comment by kevinlu1248** [comment]
I've seen the opposite happen before, where some linters prefer no newlines at the end, such as https://github.com/pytorch/ignite

**Comment by wwzeng1** [comment]
Sweep: retry

**Comment by kevinlu1248** [comment]
I think this has been implemented separately.
