### ISSUE TITLE
Sweep: Allow removing files.

### ISSUE THREAD

**Issue by stobias123** [sweepai/sweep#912]
### Details

The `entities.py` and `swee_bot.py` files only support modifying or creating files. Add support for removing files. 

### Files to change

```shell
sweepai/core/entities.py
sweepai/core/sweep_bot.py
```

**Comment by wwzeng1** [comment]
Sweep: perform this check at
try:
                self.repo.update_file(
                    file_name,
                    f'Update {file_name}',
                    new_file_contents,
                    file.sha,
                    branch=branch,
                )
                return True

**Comment by wwzeng1** [comment]
Sweep: retry

**Comment by kevinlu1248** [comment]
This is now implemented.
