### ISSUE TITLE
Sweep: Allow chunking map call to take in sublists of length 10 . also modify the chunker to support lists as well as direct inputs

### ISSUE THREAD

**Issue by wwzeng1** [sweepai/sweep#936]
Use 

chunked_results = chunker.map(file_contents, file_paths, scores, kwargs={
        "additional_metadata": {"repo_name": repo_name, "branch_name": branch_name}
    })
and 
utils/utils.py

**Comment by kevinlu1248** [comment]
sweep: Retry. Modify this at call-time in vector_db.py

**Comment by kevinlu1248** [comment]
sweep: Retry. Modify this at call-time in vector_db.py

**Comment by kevinlu1248** [comment]
sweep: Retry. Modify this at call-time in vector_db.py

**Comment by kevinlu1248** [comment]
sweep: Try again.

**Comment by kevinlu1248** [comment]
sweep: Retry. Modify this at call-time in vector_db.py. Only have 10 concurrent calls a time.
