### ISSUE TITLE
Update default sweep.yaml docs to be clearer about what the GHA_enabled option does.

### ISSUE THREAD

**Issue by Prendo93** [sweepai/sweep#940]
https://github.com/sweepai/sweep/blob/faf8ac2a0ec69868bd64dd694da670f8f3528120/sweepai/utils/config/server.py#L56

When reviewing the on-boarding PR to configure Sweep I was not clear on what exactly this option does: Allow sweep to run it's own actions, or allow it to read the output of our existing actions?

Recommend clarifying this line to eg: "# If you want to allow Sweep to read the logs and outputs from your existing Github Actions, set this to true."

**Comment by kevinlu1248** [comment]
This is outdated comments, it's on by default now. I'll clarify this in the docs. Thanks for pointing it out!

**Comment by kevinlu1248** [comment]
Fixed in https://github.com/sweepai/sweep/commit/0f05d078a756b9665dea6e22b16b21395145f325
