### ISSUE TITLE
Sweep: Create a deep link on how to configure `GPT3.5`

### ISSUE THREAD

**Issue by wmaiouiru** [sweepai/sweep#956]
Details
It is hard to find how to configure between GPT3.5 and GPT4, can you help create a deep link on `GPT3.5 tickets` to toggle between GPT3.5 and GPT4? 

Files to change
https://github.com/sweepai/sweep/blame/54076887c5ff16dd4b16f8d6ed22e5bef6b09749/README.md#L92

**Comment by wwzeng1** [comment]
Hey @wmaiouiru! Apologies, we don't allow a toggle at the moment. We want all users to be using GPT4 for their first tickets for the best experience.
