### ISSUE TITLE
Sweep: Github Actions Errors are not being parsed correctly

### ISSUE THREAD

**Issue by crespire** [sweepai/sweep#957]
### Details

When a Github action fails, Sweep is always reporting a Postgres permission error, but the suite is running without issues and has test failures to report.

**Comment by crespire** [comment]
While I was seeing test suite failures in the CI output, Sweep kept reporting a file system `Permission Denied` error so would go off on the wrong tangent.

It also started ignoring my comments and only processing CI error reports. There should be a way for me to intervine or otherwise tell it supplemental information after a CI error before starting the next generation/iteration.

**Comment by kevinlu1248** [comment]
Thanks for reporting! We're noticing this too, it has something to do with our queue implementation. We also recently changed the way we parse GitHub Actions but it doesn't seem very reliable. Do you mind sending the GitHub Action logs zip file? Assuming there's not sensitive information in there.

**Comment by crespire** [comment]
> Thanks for reporting! We're noticing this too, it has something to do with our queue implementation. We also recently changed the way we parse GitHub Actions but it doesn't seem very reliable. Do you mind sending the GitHub Action logs zip file? Assuming there's not sensitive information in there.

Happy to send some logs, but I am hesitant to post them publicly. Is there an email I can send them via?

**Comment by kevinlu1248** [comment]
Yup do you mind sending it to team@sweep.dev? Thanks!

**Comment by crespire** [comment]
Sent a set over, hope it helps! Here is what Sweeper said in response to this error:

> GitHub actions yielded the following error.
> 
> The error occurred during the execution of the following command:
> 
> ```shell
> sudo -u postgres createuser -s $USER
> could not change directory to "/home/runner/work/PressReleaseGenerator/PressReleaseGenerator": Permission denied
> ```
> 
> This command failed because the user `postgres` was unable to change the directory to "/home/runner/work/PressReleaseGenerator/PressReleaseGenerator" due to a permission denied error.
> 
> This is likely a linting or type-checking issue with the source code.

**Comment by crespire** [comment]
Sent a set over, hope it helps! Here is what Sweeper said in response to this error:

> GitHub actions yielded the following error.
> 
> The error occurred during the execution of the following command:
> 
> ```shell
> sudo -u postgres createuser -s $USER
> could not change directory to "/home/runner/work/[REPO]": Permission denied
> ```
> 
> This command failed because the user `postgres` was unable to change the directory to "/home/runner/work/[REPO]" due to a permission denied error.
> 
> This is likely a linting or type-checking issue with the source code.

**Comment by kevinlu1248** [comment]
@crespire How has it been recently?

**Comment by crespire** [comment]
> @crespire How has it been recently?

Haven't had the opportunity to try it out.
