### ISSUE TITLE
Sweep: Fix response in on_ticket.py

### ISSUE THREAD

**Issue by y0sh1** [sweepai/sweep#988]
### Details

Update the message template `payment_message_start` to add adequate spaces, to improve the sentence layout. 

### Files to change

```shell
handlers/on_ticket.py
```

**Comment by wwzeng1** [comment]
Nice ticket!

**Comment by y0sh1** [comment]
Hi @wwzeng1, The last change actually did not make the sentences better. Now we end up with an empty space before the stop if nu slow mode is active. I would say to add the leading space to the slow mode message, and put the variable for slowmode directly between the full stop of the sentence and the model indicator.
