### ISSUE TITLE
Sweep: Further improve messaging of slow mode

### ISSUE THREAD

**Issue by y0sh1** [sweepai/sweep#999]
### Details

Rework variables `slow_mode_status` and `payment_message_start` to incorporate correct use of spaces in the text. Keep in mind that `slow_mode_status` can be used as empty string if `slow_mode` is false

### Files to change

```shell
handlers/on_ticket.py
```

**Comment by y0sh1** [comment]
sweep: retry

**Comment by y0sh1** [comment]
sweep: retry

**Comment by y0sh1** [comment]
sweep: retry

**Comment by y0sh1** [comment]
sweep: retry

**Comment by wwzeng1** [comment]
Thanks y0sh1!
